### ISSUE TITLE
Revisions not working correctly

### ISSUE THREAD

**Issue by kyle-charlton** [iseulde/wp-front-end-editor#241]
Hi, we were just doing some testing to see if this plugin would work for our content writers and our clients when we discovered a problem with Revisions. 

After you make changes to the page on the front end and click the update button that shows up at the bottom of the page, the latest revision shows up blank. We also noticed that if you make changes to the page on the front end and then click the update button that shows up when you try to leave the page it only seems to make a partial revision and capture only a portion of the changes you made even though the changes are saved. We were testing the plugin on the _S starter theme using Chrome.

**Comment by iseulde** [comment]
There's been major changes since the time of this bug report. We're now using the REST API to update posts, and there will be only one revision per session for now (there will be more in the future where it makes sense). I've not noticed any blank revisions since then. Feel free to reopen if this is still an issue.
